// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQx0d3AOrtVPD_Y0P2jtvW7YBr0ro4r4',
    appId: '1:358354394564:web:268889cc8a698842d35891',
    messagingSenderId: '358354394564',
    projectId: 'testsitemanagement-5094d',
    authDomain: 'testsitemanagement-5094d.firebaseapp.com',
    storageBucket: 'testsitemanagement-5094d.appspot.com',
    measurementId: 'G-6JPLC0SGHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHEQmaB9TI5mhZU85JC3oU6bHS6n0qr_Q',
    appId: '1:358354394564:android:4c77810a08d5e28dd35891',
    messagingSenderId: '358354394564',
    projectId: 'testsitemanagement-5094d',
    storageBucket: 'testsitemanagement-5094d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCND4QB63wQrMA73paRzMraSbTo56NyPxM',
    appId: '1:358354394564:ios:a31897df46089736d35891',
    messagingSenderId: '358354394564',
    projectId: 'testsitemanagement-5094d',
    storageBucket: 'testsitemanagement-5094d.appspot.com',
    iosClientId: '358354394564-6g5pm51boank19i1llrmidijdfl8v71i.apps.googleusercontent.com',
    iosBundleId: 'com.example.managementexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCND4QB63wQrMA73paRzMraSbTo56NyPxM',
    appId: '1:358354394564:ios:a31897df46089736d35891',
    messagingSenderId: '358354394564',
    projectId: 'testsitemanagement-5094d',
    storageBucket: 'testsitemanagement-5094d.appspot.com',
    iosClientId: '358354394564-6g5pm51boank19i1llrmidijdfl8v71i.apps.googleusercontent.com',
    iosBundleId: 'com.example.managementexample',
  );
}
